<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net6.0-windows</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><TreatWarningsAsErrors>true</TreatWarningsAsErrors></PropertyGroup><ItemGroup><ProjectReference Include="..\..\src\StashKitMaker.Core\StashKitMaker.Core.csproj"/><ProjectReference Include="..\..\src\StashKitMaker.App\StashKitMaker.App.csproj"/></ItemGroup></Project>
