<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net6.0-windows</TargetFramework><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>RenzysStashKitMaker</AssemblyName><RootNamespace>StashKitMaker.App</RootNamespace><Title>Renzy's Stash Kit Maker</Title><Product>Renzy's Stash Kit Maker</Product><ApplicationIcon>Assets\OkashiPlaceholder.ico</ApplicationIcon></PropertyGroup><ItemGroup><Resource Include="Assets\OkashiPlaceholder.ico" /><ProjectReference Include="..\StashKitMaker.Core\StashKitMaker.Core.csproj" /><PackageReference Include="NAudio" Version="2.2.1" /><None Include="..\..\THIRD-PARTY-NOTICES.txt" Link="THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" /></ItemGroup></Project>
